# Generated by Django 4.1.5 on 2023-01-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='send_mail',
            field=models.BooleanField(default=False),
        ),
    ]
