# Generated by Django 4.1.5 on 2023-01-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Your username', max_length=225)),
                ('email', models.EmailField(help_text='Your email', max_length=254, unique=True)),
                ('is_verify', models.BooleanField(default=False, verbose_name='account verified')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
